#ifndef MOVERESULT_H
#define MOVERESULT_H

enum class MoveResult{

    SUCCESS, 
    INVALID_ROW_COL,
    NON_EXISTENT_PIECE,
    INVALID_PIECE_MOVE, 
    INVALID_PAWN_CAPTURE,
    PATH_NOT_CLEAR,
    ILLEGAL_FRIENDLY_FIRE,
    KING_IN_CHECK,
    LEAVES_KING_IN_CHECK,
    ERR_CASTLING_KING_MOVED,
    ERR_CASTLING_ROOK_MOVED,
    WRONG_TURN

}; 

#endif // MOVERESULT_H